version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
  snmp:
    image: prom/snmp-exporter
    ports: 
      - "9116:9116"
  # mikrotik-exporter:
  #   image: nshttpd/mikrotik-exporter:1.0.5
  #   ports:
  #     - "9121:9436"